export const labels = {
    labelInvalidField: 'Неверный формат файлов',
    labelFileWaitingForSize: 'Ожидание размера файла',
    labelFileSizeNotAvailable: 'Размер файла недоступен',
    labelFileLoading: 'Загружается',
    labelFileLoadError: 'Ошибка в процессе загрузки',
    labelFileProcessing: 'Загружается',
    labelFileProcessingComplete: 'Загрузка завершена',
    labelFileProcessingAborted: 'Загрузка отменена',
    labelFileProcessingError: 'Ошибка в процессе загрузки',
    labelFileProcessingRevertError: 'Ошибка в процессе отмены',
    labelFileRemoveError: 'Ошибка в процессе удаления',
    labelTapToCancel: 'Нажмите чтобы отменить',
    labelTapToRetry: 'Нажмите чтобы повторить',
    labelTapToUndo: 'Нажмите чтобы отменить',
    labelButtonRemoveItem: 'Удалить',
    labelButtonAbortItemLoad: 'Отменить',
    labelButtonRetryItemLoad: 'Повторить',
    labelButtonAbortItemProcessing: 'Отмена',
    labelButtonUndoItemProcessing: 'Отменить',
    labelButtonRetryItemProcessing: 'Повторить',
    labelButtonProcessItem: 'Загрузить',
    labelMaxFileSizeExceeded: 'Файл слишком большой',
    labelMaxFileSize: 'Максимальный размер файла {filesize}',
    labelFileTypeNotAllowed: 'Неверный тип файла',
    fileValidateTypeLabelExpectedTypes: 'Загрузите {allButLastType} {lastType}',
};
